# Generated by Django 6.0 on 2025-12-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Babalee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='etude',
            table='Etude',
        ),
        migrations.AlterModelTable(
            name='ev_social',
            table='Ev_Sociaux',
        ),
        migrations.AlterModelTable(
            name='guide',
            table='Guide',
        ),
        migrations.AlterModelTable(
            name='journal',
            table='journaux',
        ),
        migrations.AlterModelTable(
            name='sejour',
            table='Sejour',
        ),
    ]
