# Generated by Django 6.0 on 2025-12-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Babalee', '0002_alter_etude_table_alter_ev_social_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etude',
            options={'verbose_name': 'Etude', 'verbose_name_plural': 'Etudes'},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name': 'Guide', 'verbose_name_plural': 'Guide'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Journal', 'verbose_name_plural': 'Journaux'},
        ),
        migrations.AlterModelTable(
            name='journal',
            table='journal',
        ),
    ]
