# Generated by Django 6.0 on 2025-12-06 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Babalee', '0003_alter_etude_options_alter_guide_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bureau',
            options={'verbose_name': 'Bureau', 'verbose_name_plural': 'Bureau'},
        ),
        migrations.AlterModelOptions(
            name='celluledecom',
            options={'verbose_name': 'Cellule de com', 'verbose_name_plural': 'Cellule de com'},
        ),
        migrations.AlterModelOptions(
            name='cellulederecolte',
            options={'verbose_name': 'Cellule de recolte', 'verbose_name_plural': 'Cellule de recolte'},
        ),
        migrations.AlterModelOptions(
            name='commissionculturelle',
            options={'verbose_name': 'Commission Culturelle', 'verbose_name_plural': 'Commission Culturelle'},
        ),
        migrations.AlterModelOptions(
            name='commissionscientifique',
            options={'verbose_name': 'Commission Scientifique', 'verbose_name_plural': 'Commission Scientifique'},
        ),
        migrations.AlterModelOptions(
            name='commissionsociale',
            options={'verbose_name': 'Commission Sociale', 'verbose_name_plural': 'Commission Sociale'},
        ),
        migrations.AlterModelOptions(
            name='commissionsportive',
            options={'verbose_name': 'Commission Sportive', 'verbose_name_plural': 'Commission Sportive'},
        ),
        migrations.AlterModelOptions(
            name='elites',
            options={'verbose_name': 'Elite', 'verbose_name_plural': 'Elites'},
        ),
        migrations.AlterModelOptions(
            name='ev_culturelle',
            options={'verbose_name': 'Evenement Culturelle', 'verbose_name_plural': 'Evenements Culturelles'},
        ),
        migrations.AlterModelOptions(
            name='ev_futur',
            options={'verbose_name': 'Ev_Futur', 'verbose_name_plural': 'Evenements Futurs'},
        ),
        migrations.AlterModelOptions(
            name='ev_scientifique',
            options={'verbose_name': 'Evenement Scientifique', 'verbose_name_plural': 'Evenements Scientifiques'},
        ),
        migrations.AlterModelOptions(
            name='ev_social',
            options={'verbose_name': 'Evenement Social', 'verbose_name_plural': 'Evenements Sociaux'},
        ),
        migrations.AlterModelOptions(
            name='ev_sportif',
            options={'verbose_name': 'Evenement Sportif', 'verbose_name_plural': 'Evenements Sportifs'},
        ),
        migrations.AlterModelOptions(
            name='secretairegeneraux',
            options={'verbose_name': 'SecretaireGeneraux', 'verbose_name_plural': 'Secretaires Generaux'},
        ),
        migrations.AlterModelOptions(
            name='sejour',
            options={'verbose_name': 'Sejour', 'verbose_name_plural': 'Sejour'},
        ),
        migrations.AlterModelTable(
            name='bureau',
            table='Bureau',
        ),
        migrations.AlterModelTable(
            name='celluledecom',
            table='Celluledecom',
        ),
        migrations.AlterModelTable(
            name='cellulederecolte',
            table='Cellulederecolte',
        ),
        migrations.AlterModelTable(
            name='commissionculturelle',
            table='CommissionCulturelle',
        ),
        migrations.AlterModelTable(
            name='commissionscientifique',
            table='CommissionScientifique',
        ),
        migrations.AlterModelTable(
            name='commissionsociale',
            table='CommissionSociale',
        ),
        migrations.AlterModelTable(
            name='commissionsportive',
            table='CommissionSportive',
        ),
        migrations.AlterModelTable(
            name='elites',
            table='Elites',
        ),
        migrations.AlterModelTable(
            name='ev_culturelle',
            table='Ev_Culturelle',
        ),
        migrations.AlterModelTable(
            name='ev_futur',
            table='Ev_Futur',
        ),
        migrations.AlterModelTable(
            name='ev_scientifique',
            table='Ev_Scientifique',
        ),
        migrations.AlterModelTable(
            name='ev_social',
            table='Ev_Social',
        ),
        migrations.AlterModelTable(
            name='ev_sportif',
            table='Ev_Sportif',
        ),
        migrations.AlterModelTable(
            name='secretairegeneraux',
            table='SecretaireGeneraux',
        ),
    ]
